# Generated by Django 4.0 on 2022-02-22 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0003_alter_factors_creat_date_alter_factors_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 22, 22, 56, 33, 875449), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 22, 22, 56, 33, 875449), verbose_name='تاریخ پرداخت'),
        ),
    ]
