# Generated by Django 4.0.4 on 2022-04-11 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0013_alter_factors_creat_date_alter_factors_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 19, 43, 35, 462021), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 19, 43, 35, 462021), verbose_name='تاریخ پرداخت'),
        ),
    ]
