# Generated by Django 4.0 on 2022-04-13 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0014_alter_factors_creat_date_alter_factors_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='facotrproduct',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 10, 37, 7, 964870), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 10, 37, 7, 964870), verbose_name='تاریخ پرداخت'),
        ),
    ]
