# Generated by Django 4.0 on 2022-04-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0015_facotrproduct_unit_price_alter_factors_creat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factors',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='کد پیگیری'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 11, 32, 59, 735082), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 11, 32, 59, 735082), verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='state',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'پرداخت نشده'), (2, 'در انتظار پرداخت'), (1, 'پرداخت شده')], default=1, verbose_name='وضعیت پرداخت'),
        ),
    ]
