# Generated by Django 4.0 on 2022-04-23 11:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0016_factors_ref_id_alter_factors_creat_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 16, 12, 2, 192411), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 23, 16, 12, 2, 191411), verbose_name='تاریخ پرداخت'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='state',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'پرداخت نشده'), (2, 'در انتظار پرداخت'), (1, 'پرداخت شده')], default=1, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='مبلغ نهایی'),
        ),
    ]
