# Generated by Django 4.0 on 2022-04-29 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factor', '0018_alter_factors_creat_date_alter_factors_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factors',
            name='creat_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 23, 19, 10, 336948), verbose_name='تاریخ ایجاد فاکتور'),
        ),
        migrations.AlterField(
            model_name='factors',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 23, 19, 10, 336948), verbose_name='تاریخ پرداخت'),
        ),
    ]
