# Generated by Django 4.0.4 on 2022-04-11 14:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=40, verbose_name='کد تراکنش')),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 11, 19, 8, 54, 53199), verbose_name='تاریخ پرداخت')),
                ('state', models.IntegerField(choices=[(0, 'پرداخت ناموفق'), (1, 'پرداخت موفق'), (2, 'در انتظار پرداخت')], default=2, verbose_name='وضعیت تراکنش')),
                ('ref_id', models.CharField(blank=True, default='', max_length=20, verbose_name='کد پیگیری')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'جدول تراکنش',
            },
        ),
    ]
