# Generated by Django 4.0 on 2022-04-13 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_alter_transactions_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 13, 11, 32, 59, 727081), verbose_name='تاریخ پرداخت'),
        ),
    ]
