# Generated by Django 4.0 on 2022-04-29 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_alter_transactions_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 23, 18, 3, 563129), verbose_name='تاریخ پرداخت'),
        ),
    ]
