# Generated by Django 4.0 on 2022-05-02 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0007_alter_transactions_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='payment_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 5, 2, 17, 0, 39, 286428), verbose_name='تاریخ پرداخت'),
        ),
    ]
