# Generated by Django 4.0 on 2022-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, default=98, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, choices=[('1', 'تهران'), ('2', 'خوزستان'), ('3', 'بوشهر'), ('4', 'خراسان رضوی'), ('5', 'اصفهان'), ('6', 'فارس'), ('7', 'آذربایجان شرقی'), ('8', 'مازندران'), ('9', 'کرمان'), ('10', 'البرز'), ('11', 'گیلان'), ('12', 'کهگیلویه و بویراحمد'), ('13', 'آذربایجان غربی'), ('14', 'هرمزگان'), ('15', 'مرکزی'), ('16', 'یزد'), ('17', 'کرمانشاه'), ('14', 'هرمزگان'), ('14', 'هرمزگان'), ('14', 'هرمزگان'), ('14', 'هرمزگان'), ('14', 'هرمزگان')], max_length=2, verbose_name='استان'),
        ),
    ]
