# Generated by Django 4.0 on 2022-01-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, default=1, verbose_name='تعداد محصول')),
                ('total_price', models.PositiveIntegerField(verbose_name='مبلغ نهایی')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='نام محصول')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='نام کاربر')),
            ],
        ),
    ]
