# Generated by Django 4.0 on 2022-02-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='قیمت واحد'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد محصول'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='مبلغ نهایی'),
        ),
    ]
