# Generated by Django 4.0 on 2022-02-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_unit_price_alter_cart_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='store_pro',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='انبار محصول'),
        ),
    ]
