# Generated by Django 4.0 on 2022-02-22 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_store_pro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='store_pro',
        ),
    ]
