# Generated by Django 4.0 on 2022-01-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorise',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('count', models.PositiveIntegerField(blank=True, default=0, verbose_name='تعداد محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول')),
                ('deleted', models.BooleanField(blank=True, default=False, verbose_name='محصول حذف شده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.subcategorise', verbose_name='نام دسته بندی')),
            ],
        ),
    ]
